### ISSUE TITLE
How is the CC licensed?

### ISSUE THREAD

**Issue by zippy1981** [gtathub/js-soap-client#4]
You claim this is CC licensed, but you forked it from a GPL project. Did you have permission to relicense the fork?

**Comment by gtathub** [comment]
Initially my modifications based on v2.1 from here: http://www.guru4.net/articoli/javascript-soap-client/en/. This is indeed licensed under CC. On merging with 2.4 I forgot to update the license. Many thanks for the hint. I will fix it.
